# Generated by Django 5.2 on 2025-06-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CipherResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cipher_results/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
